global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9113']
      
  - job_name: 'tarantool'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8088']    